apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  serviceAccountName: log-summarizer-sa
  containers:
  - name: debug-container
    image: bitnami/kubectl:latest
    command: ["/bin/sh"]
    args: ["-c", "sleep infinity"]
    tty: true
    stdin: true
  restartPolicy: Never

