apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    worker_processes  1;

    events {
        worker_connections  1024;
    }

    http {
        # Define a custom log format (optional)
        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

        # Redirect access logs to stdout using the custom format
        access_log /dev/stdout main;

        # Redirect error logs to stderr with warning level
        error_log /dev/stderr warn;

        server {
            listen       80;
            server_name  localhost;

            location / {
                return 200 "Hello from Nginx\n";
            }
        }
    }

